language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t LucasAtMogree/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true LucasAtMogree/docker-react npm run test