language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t lucas-at-mogree/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lucas-at-mogree/docker-react npm run test